<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Script_1743215796</AssemblyName>
    <OutputPath>M:\HawkEngine\HawkEngine_Warhammer40K\MyGameMaker\x64\Release\..\..\Script\obj</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>0169,0414,0649,0626,0642</NoWarn>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.Runtime.Extensions" />
    <Reference Include="System.Runtime.InteropServices" />
    <Reference Include="System.Runtime.Numerics" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Runtime.Serialization.Primitives" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
